server:
  port: 8080
  servlet:
    context-path: /

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
  batch:
    job:
      enabled: false
  devtools:
    add-properties: true
    livereload:
      enabled: true
    restart:
      exclude: static/**,public/**
  flyway:
    createSchemas: true
    group: true
    table: flyway_schema_history
  management:
    endpoints:
      web:
        exposure:
          include: info,health,flyway
    server:
      port: 9095

openemr:
  token_url: "https://open-emr.ohmydev.asia/oauth2/default/token"
  api_url: "https://open-emr.ohmydev.asia/apis/default/api/"
  client_id: "IMJvEKUaawWWj8ZCBrcc39V9RPUOzEtDHoIWDPoPpbs"
  grant_type: "password"
  user_role: "users"
  scope: "openid api:oemr api:fhir api:port user/allergy.read user/allergy.write user/appointment.read user/appointment.write user/dental_issue.read user/dental_issue.write user/document.read user/document.write user/drug.read user/encounter.read user/encounter.write user/facility.read user/facility.write user/immunization.read user/insurance.read user/insurance.write user/insurance_company.read user/insurance_company.write user/insurance_type.read user/list.read user/medical_problem.read user/medical_problem.write user/medication.read user/medication.write user/message.write user/patient.read user/patient.write user/practitioner.read user/practitioner.write user/prescription.read user/procedure.read user/soap_note.read user/soap_note.write user/surgery.read user/surgery.write user/vital.read user/vital.write user/AllergyIntolerance.read user/CareTeam.read user/Condition.read user/Encounter.read user/Immunization.read user/Location.read user/Medication.read user/MedicationRequest.read user/Observation.read user/Organization.read user/Organization.write user/Patient.read user/Patient.write user/Practitioner.read user/Practitioner.write user/PractitionerRole.read user/Procedure.read patient/encounter.read patient/patient.read patient/Encounter.read patient/Patient.read"
  username: "admin"
  password: "admin"